### ISSUE TITLE
Roadmap to v1

### ISSUE THREAD

**Issue by keroxp** [keroxp/servest#83]
- [x] Auth Middleware
- [x] Nested Router
- [x] Type-Aware middleware system #88
- [x] WebSocket Integration
- [x] HTTP testing api
- [x] Serve JSX
- [x] Cookie support
- [x] Body parsers (json, form, multipart)
- [ ] Migrate `serveio` and Server API into `std/http`
  - delayed after Deno@v1 released

**Comment by keroxp** [comment]
Now all ready to be v1!
